### ISSUE TITLE
Glider names

### ISSUE THREAD

**Issue by Gollum69** [LlemonDuck/easy-teleports#11] opened 2023-07-02 20:00 UTC
Currently the Glider names are so weird and I always mix them up, which I assume is similar to how players feel about the Pharoah's Sceptre or Xeric's Talisman etc, it would be really nice if we could rename the Glider names to something more suitable

**Comment by LlemonDuck** [comment] 2023-08-28 18:49
Duplicate of #5

**Closed by LlemonDuck** 2023-08-28 18:49 UTC
